<?php

namespace AppBundle\Repository;

/**
 * InsectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsectRepository extends \Doctrine\ORM\EntityRepository
{
}
